name: Build verify

on:
  pull_request:
    branches:
      - main
      - "feat/**"

jobs:
  build-ui:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.17.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0

      - name: Npm install
        run: npm ci

      - name: Add env file
        run: |
          touch .env.production
          echo MONGODB_AUTH=${{ secrets.MONGODB_AUTH }} >> .env.production
          cat .env.production

      - name: Npm run Build
        run: npm run build
